@startuml
title 会議室予約

class 予約 {
  予約時間
  予約者
  会議室
  +予約結果 getResult(予約リスト)
}

class 予約リスト {
  List<予約>
  +重複予約リスト 重複チェック(予約時間)
}
class 重複予約リスト {
  List<予約>
}

class 予約時間 {
  開始時間
  終了時間
  + boolean isかぶってる(予約時間)
}

class 開始時間 {
}
class 終了時間 {
}

class 予約結果{
  Either<予約結果NG, 予約結果OK>
}

class 予約結果OK {
  予約
}
class 予約結果NG {
  重複予約リスト
  + inEmpty()
}

class 予約者 {
}

class 会議室 {
  + create(会議室名)
}
class 会議室名 {
}

予約リスト -->"0..*" 予約
重複予約リスト -->"0..*" 予約

予約 --> "1"予約者
予約 --> "1"予約時間
予約 --> "1"会議室

予約結果 -->"0,1" 予約結果OK
予約結果 -->"0,1" 予約結果NG

予約結果OK -->"1" 予約
予約結果NG -->"1" 重複予約リスト

予約時間 -->"1" 開始時間
予約時間 -->"1" 終了時間

会議室 -->"1" 会議室名

@enduml