@startuml
title HUGっと！プリキュア

class HUGっとプリキュア {
  野乃はな
  薬師寺さあや
  輝木ほまれ
  愛崎えみる
  ルールー・アムール
  +HUGっとプリキュア_変身 transform()
}

class HUGっとプリキュア_変身 {
  キュアエール
  キュアアンジュ
  キュアエトワール
  キュアマシェリ
  キュアアムール
  +HUGっとプリキュア_チアフルスタイル transform()
}
class HUGっとプリキュア_チアフルスタイル {
  キュアエール_チアフルスタイル
  キュアアンジュ_チアフルスタイル
  キュアエトワール_チアフルスタイル
  キュアマシェリ_チアフルスタイル
  キュアアムール_チアフルスタイル
}

package キュアエール {
    
    class 野乃はな {
      + キュアエール transform()
    }
    
    class キュアエール {
      ミライクリスタル・ピンク
      + キュアエール_チアフルスタイル tramsform()
    }
    
    class キュアエール_チアフルスタイル {
    }
    
    class ミライクリスタル_ピンク {
    }
}

HUGっとプリキュア --> 野乃はな
HUGっとプリキュア_変身 --> キュアエール
キュアエール --> ミライクリスタル_ピンク
HUGっとプリキュア_チアフルスタイル --> キュアエール_チアフルスタイル

@enduml