@startuml
APサービス -> リポジトリ : 今回の登場人物を取得
APサービス <-- リポジトリ : 登場人物
APサービス -> "ドメインサービス(onAir)" : プリキュアと敵を渡す
"ドメインサービス(onAir)" -> 社員 : 発注
社員 --> "ドメインサービス(onAir)": オシマイダー怪
"ドメインサービス(onAir)" -> "HUGっと！プリキュア" : 変身する
"ドメインサービス(onAir)" <-- "HUGっと！プリキュア" : 変身後

"ドメインサービス(onAir)" -> "ドメインサービス(合体技)" : 必殺技を撃つ

@enduml